version: '3.9'

services:
  dev_env:
    container_name: ${container_name}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        port: ${port}
        ip: ${ip}
        base_dir: ${base_dir}
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ./extensions:${base_dir}/extensions
      - ./notebooks:${base_dir}/notebooks
      - ./jupyter_server_config.py:/root/.jupyter/jupyter_server_config.py
    ports:
      - ${port}:${port}

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
